name: first-workflow
on:
  push:
    branches: [ "feature/first-workflow" ]
jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          server-id: "github"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
      - name: Generate Jar file
        run: gradle build
      - name: Run generated Jar file
        run: java -jar ./app/build/libs/app.jar